wandb_version: 1

experiment_name:
  desc: null
  value: test
dataset:
  desc: null
  value: nl-en
language:
  desc: null
  value: nl
token_len:
  desc: null
  value: 200
prefix_len:
  desc: null
  value: 50
num_trials:
  desc: null
  value: 7
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716983436
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
